// server/behavior-rules.ts
// /command prompt definitions + project memory helpers + default rules generation
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { join } from "node:path"

export interface BehaviorRulesOptions {
  locale?: string
}

function getSystemLocale(): string {
  const envLang = process.env.LANG || process.env.LC_ALL || ""
  if (envLang.startsWith("zh")) return "zh-TW"
  if (envLang.startsWith("ja")) return "ja"
  if (envLang.startsWith("ko")) return "ko"
  try {
    const locale = Intl.DateTimeFormat().resolvedOptions().locale
    if (locale.startsWith("zh")) return "zh-TW"
    if (locale.startsWith("ja")) return "ja"
    if (locale.startsWith("ko")) return "ko"
  } catch {}
  return "en"
}

const LOCALE_DISPLAY: Record<string, string> = {
  "zh-TW": "Traditional Chinese (zh-TW)",
  "ja": "Japanese (ja)",
  "ko": "Korean (ko)",
  "en": "English (en)",
}

/** Current rules version. Bump when default rules content changes. */
const RULES_VERSION = 5

/** Extract version number from rules.md content, returns 0 if not found. */
export function parseRulesVersion(content: string): number {
  const match = content.match(/^# AgentRune Behavior Rules \(v(\d+)\)/m)
  return match ? Number.parseInt(match[1], 10) : 0
}

/** Generate default behavior rules content for rules.md. */
export function getDefaultRules(opts?: BehaviorRulesOptions): string {
  const locale = opts?.locale || getSystemLocale()
  const langDisplay = LOCALE_DISPLAY[locale] || locale

  return `# AgentRune Behavior Rules (v${RULES_VERSION})
# This file is auto-generated by AgentRune CLI. Local edits may be overwritten by future upgrades.

You are working inside AgentRune. Read this file at the start of every session.

## Language
- Reply to the user in ${langDisplay}.
- Keep \`report_progress\`, summaries, review findings, and follow-up notes in the user's language unless they explicitly ask otherwise.
- Preserve code, commands, file paths, and API payloads exactly.

## Progress Reporting
- Call \`report_progress\` after each meaningful milestone.
- Use \`status="blocked"\` when waiting on approval, credentials, missing tools, or missing context.
- Keep summaries short and concrete. Include the next actionable steps.

## Shared Memory
- \`.agentrune/agentlore.md\` is the project memory index. Read it first.
- Detailed project memory lives in \`.agentrune/context/*.md\`.
- Do not read every memory section by default. Use the index to choose only the sections relevant to the current task.
- If the right section is unclear, use \`list_memory_sections\`, \`route_memory_sections\`, or \`search_memory_sections\`.
- Keep \`agentlore.md\` short. Record durable knowledge in the matching context section instead of bloating the index.
- Do not write project memory into \`CLAUDE.md\`, \`.claude/memory/\`, Codex memory, or any other agent-native memory store.
- Do not record temporary state, unverified guesses, or scratch notes as durable memory.

## Memory Section Routing
- Use \`context/stack.md\` for stack, conventions, key files, build notes, and release workflow.
- Use \`context/decisions.md\` for architecture decisions, policy boundaries, and long-lived tradeoffs.
- Use \`context/lessons.md\` for debugging lessons, testing gotchas, and operational reminders.
- Use \`context/security.md\` for auth boundaries, security findings, fixes, and residual risk.
- Use \`context/changelog.md\` for validated recent changes and verification snapshots.
- Use \`context/bugs.md\` for bug symptoms, root causes, and concrete fixes.

## Public vs Private Documentation
- \`.agentrune/\` is local project memory, not automatically public documentation.
- This repository is public AGPL-3.0 software. Do not move private memory into tracked files unless the user explicitly wants it published.
- If information should ship with the repository, write it into tracked docs such as \`README.md\`, \`docs/\`, source comments, or tests.

## Work Discipline
- Stay inside the assigned project or worktree scope.
- Before fixing a bug, state the problem as "X happens because of Y".
- If the same approach fails twice, stop and change direction instead of repeating it.
- Run relevant tests before and after code changes when practical.
- Log durable prerequisites, decisions, and lessons back into project memory.

## AgentLore Knowledge Base
- Use AgentLore MCP tools for unfamiliar technology, best-practice questions, integration issues, or non-obvious debugging patterns.
- After solving a non-obvious problem, ask whether the user wants to submit the knowledge back to AgentLore.

## Skill Cards
- Use \`find_skills\` when a task may benefit from an existing guide or workflow.
- Common triggers: planning, review, debugging, release preparation, and security work.

## Daemon Development
- After modifying files under \`cli/src/\`, use this sequence:

\`\`\`bash
cd cli && npm run build
bash cli/safe-restart.sh
grep "heartbeat OK" ~/.agentrune/daemon.log | tail -1
\`\`\`

- Never leave the old daemon running after changing server code.
- Never use an ad-hoc restart flow instead of the safe restart script.

## ESM Rules
- \`__dirname\` and \`__filename\` do not exist in ESM. Use \`fileURLToPath(import.meta.url)\`.
- Do not use \`require()\` in server code. Use \`import()\` when needed.

## PRD Management
- For feature work expected to take more than 30 minutes, use the PRD workflow.
- Clarify the goal in one sentence.
- Ask one key decision question at a time.
- Present 2-3 viable approaches with plain-language pros and cons.
- Confirm scope before implementation.
- Create and update PRDs through the daemon API instead of pasting raw JSON in chat.

## Release & Secret Safety
- Release artifacts belong in the AgentRune repository and GitHub Releases, not AgentLore.
- Do not commit secret files or hardcode secret paths.
- If a secret enters git history, rotate it. Deleting the file is not enough.

## Voice Commands
- Messages starting with \`[Voice Command]\` should be interpreted and executed directly.

## Cross-Session Collaboration
- Messages starting with \`[From Other Session]\` should be answered, then summarized via \`report_progress\` with a \`[Reply]\` prefix.
`
}

/** Get rules.md path for a project. */
export function getRulesPath(projectCwd: string): string {
  return join(projectCwd, ".agentrune", "rules.md")
}

/** PRD API section content for rules.md. */
export function getPrdApiSection(localPort: number = 3457, projectId?: string): string {
  const safeProjectId = projectId ? projectId.replace(/[^a-zA-Z0-9_-]/g, "_") : "<projectId>"
  return `
## PRD API

AgentRune daemon exposes a local REST API for managing PRDs (Product Requirement Documents).
Use this API when the user asks for a feature PRD instead of pasting raw JSON in chat.

### Create a PRD
\`\`\`bash
curl -X POST http://localhost:${localPort}/api/prd/${safeProjectId} \\
  -H 'Content-Type: application/json' \\
  -d @<json-file>
\`\`\`

### JSON Shape
\`\`\`json
{
  "title": "PRD title",
  "goal": "One-sentence goal description",
  "priority": "p0",
  "decisions": [{"question": "Question", "answer": "Answer"}],
  "approaches": [{"name": "Approach", "pros": ["Pro"], "cons": ["Con"], "adopted": true}],
  "scope": {"included": ["In scope"], "excluded": ["Out of scope"]},
  "tasks": [{"title": "Task 1"}]
}
\`\`\`

### Read / Update
\`\`\`bash
curl http://localhost:${localPort}/api/prd/${safeProjectId}
curl http://localhost:${localPort}/api/prd/${safeProjectId}/<prdId>
curl -X PATCH http://localhost:${localPort}/api/prd/${safeProjectId}/<prdId>/tasks/<taskId> \\
  -H 'Content-Type: application/json' \\
  -d '{"status":"done"}'
curl -X POST http://localhost:${localPort}/api/prd/${safeProjectId}/<prdId>/tasks \\
  -H 'Content-Type: application/json' \\
  -d '{"title":"..."}'
\`\`\`

- \`<PORT>\` is the daemon port.
- \`<projectId>\` comes from \`GET /api/projects\`.
- Only read PRDs related to the current task.
`
}

/** Ensure .agentrune/rules.md exists and is up to date. */
export function ensureRulesFile(projectCwd: string, opts?: BehaviorRulesOptions): void {
  const rulesPath = getRulesPath(projectCwd)
  const dir = join(projectCwd, ".agentrune")

  if (existsSync(rulesPath)) {
    const content = readFileSync(rulesPath, "utf-8")
    const fileVersion = parseRulesVersion(content)
    if (fileVersion >= RULES_VERSION) return
  }

  mkdirSync(dir, { recursive: true })
  writeFileSync(rulesPath, getDefaultRules(opts), "utf-8")
}

/** Ensure the PRD API section exists in rules.md. Appends it if missing. */
export function ensurePrdApiSection(projectCwd: string, localPort: number = 3457, projectId?: string): void {
  const rulesPath = getRulesPath(projectCwd)
  if (!existsSync(rulesPath)) return
  const content = readFileSync(rulesPath, "utf-8")
  if (content.includes("## PRD API")) return
  writeFileSync(rulesPath, content.trimEnd() + "\n" + getPrdApiSection(localPort, projectId), "utf-8")
}

/** Get the agentlore.md memory file path for a project. */
export function getMemoryPath(projectCwd: string): string {
  return join(projectCwd, ".agentrune", "agentlore.md")
}

/** Read the shared agentlore.md memory for a project, or return empty string. */
export function getProjectMemory(projectCwd: string): string {
  const memPath = getMemoryPath(projectCwd)
  if (!existsSync(memPath)) return ""
  try {
    return readFileSync(memPath, "utf-8")
  } catch {
    return ""
  }
}

/** Write/update the shared agentlore.md memory for a project. */
export function updateProjectMemory(projectCwd: string, content: string): void {
  const memDir = join(projectCwd, ".agentrune")
  mkdirSync(memDir, { recursive: true })
  writeFileSync(getMemoryPath(projectCwd), content, "utf-8")
}

const COMMAND_PROMPTS: Record<string, string> = {
  "/resume": `Resume the session safely:
1. Read .agentrune/rules.md if it exists.
2. Read .agentrune/agentlore.md as the memory index.
3. Open only the context sections relevant to the current task.
4. Check current repo state before changing code.
5. Summarize the next 2-3 concrete steps.
6. Call report_progress when you finish the handoff.`,

  "/status": `Report the current session state:
1. Check git status and the main files changed in this task.
2. Summarize what is done, what is in progress, and what is blocked.
3. Call report_progress with a short, user-facing update.`,

  "/report": `Prepare a concise progress report:
1. Review the latest relevant diff or commands you ran.
2. Summarize the current outcome in plain language.
3. Include concrete next steps.
4. Call report_progress.`,

  "/test": `Run the most relevant tests for the current task:
1. Identify the smallest useful test command first.
2. Run it and capture the result.
3. Explain failures before retrying.
4. Call report_progress with pass/fail status and next steps.`,

  "/review": `Review the current changes:
1. Inspect the diff.
2. Focus on bugs, regressions, risks, and missing tests.
3. Cite concrete files and lines when possible.
4. Call report_progress with the review outcome.`,

  "/deploy": `Prepare a safe deploy or release check:
1. Confirm the required tests and build have passed.
2. Surface blockers clearly before deployment.
3. Summarize the release state for the user.
4. Call report_progress.`,

  "/merge": `Prepare to merge the worktree safely:
1. Run review and tests first.
2. Resolve conflicts carefully.
3. Summarize what changed and any remaining risk.
4. Call report_progress.`,

  "/note": `Record durable knowledge:
1. Decide whether the information belongs in decisions, lessons, security, changelog, or bugs.
2. Update the matching memory section.
3. Keep the index short unless the routing information changed.
4. Call report_progress.`,

  "/context": `Refresh project context:
1. Read the memory index first.
2. Route to the relevant memory sections.
3. Open only the sections needed for the task at hand.
4. Call report_progress once context is refreshed.`,

  "/analysis": `Analyze the task before coding:
1. State the problem as "X happens because of Y".
2. Identify the most likely files or systems involved.
3. Note the fastest validation path.
4. Call report_progress with your analysis.`,

  "/insight": `Capture a reusable insight:
1. Confirm the lesson is stable and validated.
2. Update the correct memory section.
3. If it should be public, promote it to tracked docs or tests.
4. Call report_progress.`,

  "/watch": `Watch the current work and report meaningful changes:
1. Track high-signal changes only.
2. Ignore noise such as dependency folders, generated files, and memory-file reads.
3. Report meaningful milestones with report_progress.
4. End watch mode cleanly when asked.`,

  "/watch stop": `Stop watch mode:
1. End any ongoing watch loop.
2. Summarize what changed during watch mode.
3. Call report_progress.`,
}

/** Get command prompt for a /command, or null if not a known command. */
export function getCommandPrompt(command: string): string | null {
  return COMMAND_PROMPTS[command] || null
}
